### ISSUE TITLE
Scrapping scripts for GEOlino training set

### ISSUE THREAD

**Issue by ThaminduR** [Jmallins/ZEST#2]
I can't seem find the scrapping scripts mentioned in the paper. Can you add them to the repository ?

**Comment by Jmallins** [comment]
Hi @ThaminduR I'm really sorry about that. The reason it is not uploaded it because the geolino changed their site and my scraping script no longer works. 

Just to note we used the dataset from https://aclanthology.org/C12-1065.pdf (which from memory was about half the size of the scrape.) Where you can email the authors to get it.  

I also did a bit of digging and it looks like http://www.sfs.uni-tuebingen.de/~zweiss/rsrc/Weiss.Meruers-18-COLING-Poster.pdf will also give out geolino data. 

I'm no longer at university, so I don't have have a ton of time to dedicate to fixing it (I would also need work to sign off on the code) .

**Comment by ThaminduR** [comment]
Hi @Jmallins, I got the dataset from authors. 
Can you also mention the resource requirements for the complete model. I saw that you have mentioned it takes about a week to run on a tesla p100. What about the memory consumption?

**Comment by Jmallins** [comment]
Great. 

Regarding GPU memory, I think it was close to 12GB. For ram, it used about 32 GB, but I'm not 100% certain about these numbers.   What card would you want to use?

**Comment by Jmallins** [comment]
To follow up, the size is about 23 transformer layers, but only 15 are active per batch. The data for the paper was ~ 40M datapoints.

**Comment by Jmallins** [comment]
BTW @ThaminduR if you are interested in non-English simplification there is also https://github.com/facebookresearch/muss/ (although they don't provide a pre-trained German model)

**Comment by ThaminduR** [comment]
Thanks for the info. 
I'm planning to run this on a RTX 6000 GPU. Also I have looked into the MUSS papers as well. I'm interested in your paper and reproducing your results. 
Currently I'm trying to run this on Google Colab, which obviously doesn't have the capability. Is there any chance we can run the training instances one by one ?

**Comment by Jmallins** [comment]
Great! Please feel free to reach out if you have any issues and I'll try and help. Also, I will try and update the readme tommorow with some advice on preprocessing the data. 

"Is there any chance we can run the training instances one by one ?" - to be faithful to the paper, I don't think this would be possible, as the code switches between datasets (which are all held in memory)  and transformer layers every minibatch. However, I did consider (and even had some code) for training on one task at a time, but I never got around to trying it.

**Comment by ThaminduR** [comment]
I have some questions regarding the code and running this. I can send a mail to your email address in the paper, if it's still active.

**Comment by Jmallins** [comment]
It will be deactivated soon and I only really check it onces a month (so things might get lost). It's probably best to send it to jsmallins@gmail.com .

**Comment by Jmallins** [comment]
BTW @ThaminduR  could you let me know when you've copied my email, as I don't wish for it to be crawled.

**Comment by ThaminduR** [comment]
I copied it.

**Comment by Jmallins** [comment]
thank you.
