### ISSUE TITLE
Error during translation

### ISSUE THREAD

**Issue by ThaminduR** [Jmallins/ZEST#3]
An error occurs during translation . 

Following code is from `onmt/translate/translation.py` ([Line:74](https://github.com/Jmallins/ZEST/blob/master/onmt/translate/translation.py#L74)).
Here the list is empty due to empty `translation_batch["maxvecs"]`.

```       preds, pred_score, attn, gold_score,maxvecs, indices = list(zip(
            *sorted(zip(translation_batch["predictions"],
                        translation_batch["scores"],
                        translation_batch["attention"],
                        translation_batch["gold_score"],
                        translation_batch["maxvecs"],
                        batch.indices.data),
                    key=lambda x: x[-1]))) 
```

This happens due to following, which is from `onmt/translate/translator.py` ([Line:769](https://github.com/Jmallins/ZEST/blob/master/onmt/translate/translator.py#L769)).
Here the `maxvecs` is set to an empty list.

```
        results["scores"] = beam.scores
        results["predictions"] = beam.predictions
        results["attention"] = beam.attention
        results["maxvecs"] = []
```

**Comment by Jmallins** [comment]
Thank you. I've fixed this now. 

On a side note, I've updated the number of training steps in the readme (feel free to leave this untouched, as your dataset is small).
I've also fixed the issues with multi-decoding. You now need to pass the flag -multi true.

I've verified everything worked by overfitting to a small dataset.

**Comment by ThaminduR** [comment]
Thank you.
